'use client';

/**
 * Trip Plan Detail Page
 * Display AI-generated trip plan with timeline
 */

import { use, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Calendar,
  MapPin,
  DollarSign,
  Users,
  Lightbulb,
  AlertTriangle,
  ArrowLeft,
  Share2,
  Clock,
  Utensils,
  Home,
  Train,
  Sparkles,
} from 'lucide-react';
import Link from 'next/link';
import { toast } from 'sonner';

interface TripPlan {
  _id: string;
  title: string;
  origin: string;
  destinations: Array<{ _id: string; name: string; images: string[]; province: string }>;
  days: number;
  budget: number;
  travelers: number;
  travelStyle: string;
  startDate: string;
  endDate: string;
  itinerary: Array<{
    day: number;
    date: string;
    morning: { activities: string[]; estimatedCost: number };
    afternoon: { activities: string[]; estimatedCost: number };
    evening: { activities: string[]; estimatedCost: number };
    accommodation: string;
    totalDayCost: number;
  }>;
  transportation: { type: string; details: string; cost: number };
  budgetBreakdown: {
    transportation: number;
    accommodation: number;
    food: number;
    activities: number;
    other: number;
    total: number;
  };
  tips: string[];
  warnings: string[];
  aiGenerated: boolean;
  aiModel: string;
  views: number;
  createdAt: string;
}

export default function PlanDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const router = useRouter();
  const resolvedParams = use(params);
  const [plan, setPlan] = useState<TripPlan | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchPlan();
  }, [resolvedParams.id]);

  const fetchPlan = async () => {
    try {
      const res = await fetch(`/api/trip-plans/${resolvedParams.id}`);
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error);
      }

      setPlan(data.data.plan);
    } catch (error: any) {
      toast.error(error.message || 'Không thể tải kế hoạch');
      router.push('/my-plans');
    } finally {
      setLoading(false);
    }
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: plan?.title,
        text: `Kế hoạch du lịch ${plan?.days} ngày`,
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(window.location.href);
      toast.success('Link đã được copy!');
    }
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('vi-VN').format(amount) + 'đ';
  };

  if (loading) {
    return (
      <div className="container mx-auto px-4 py-12">
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
        </div>
      </div>
    );
  }

  if (!plan) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="container mx-auto px-4 max-w-5xl">
        {/* Header */}
        <div className="mb-8">
          <Button variant="outline" size="sm" asChild className="mb-4">
            <Link href="/my-plans">
              <ArrowLeft className="mr-2 w-4 h-4" />
              Quay lại
            </Link>
          </Button>

          <div className="flex items-start justify-between">
            <div>
              {plan.aiGenerated && (
                <Badge className="mb-3 bg-gradient-to-r from-blue-600 to-purple-600">
                  <Sparkles className="w-3 h-3 mr-1" />
                  AI Generated by {plan.aiModel}
                </Badge>
              )}
              <h1 className="text-3xl font-bold mb-2">{plan.title}</h1>
              <p className="text-gray-600">
                Tạo lúc {new Date(plan.createdAt).toLocaleDateString('vi-VN', { dateStyle: 'full' })}
              </p>
            </div>
            <Button variant="outline" onClick={handleShare}>
              <Share2 className="mr-2 w-4 h-4" />
              Chia sẻ
            </Button>
          </div>
        </div>

        {/* Overview */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Tổng quan chuyến đi</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div>
                <div className="flex items-center gap-2 text-gray-600 mb-1">
                  <MapPin className="w-4 h-4" />
                  <span className="text-sm">Hành trình</span>
                </div>
                <p className="font-medium">
                  {plan.origin} → {plan.destinations.map((d) => d.name).join(', ')}
                </p>
              </div>

              <div>
                <div className="flex items-center gap-2 text-gray-600 mb-1">
                  <Calendar className="w-4 h-4" />
                  <span className="text-sm">Thời gian</span>
                </div>
                <p className="font-medium">
                  {plan.days} ngày ({new Date(plan.startDate).toLocaleDateString('vi-VN')})
                </p>
              </div>

              <div>
                <div className="flex items-center gap-2 text-gray-600 mb-1">
                  <Users className="w-4 h-4" />
                  <span className="text-sm">Số người</span>
                </div>
                <p className="font-medium">{plan.travelers} người</p>
              </div>

              <div>
                <div className="flex items-center gap-2 text-gray-600 mb-1">
                  <DollarSign className="w-4 h-4" />
                  <span className="text-sm">Ngân sách</span>
                </div>
                <p className="font-medium">{formatCurrency(plan.budget)}/người</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Itinerary Timeline */}
        <div className="mb-8">
          <h2 className="text-2xl font-bold mb-6">Lịch trình chi tiết</h2>
          <div className="space-y-6">
            {plan.itinerary.map((day, idx) => (
              <Card key={idx} className="overflow-hidden">
                <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-sm opacity-90">Ngày {day.day}</p>
                      <p className="font-bold">
                        {new Date(day.date).toLocaleDateString('vi-VN', {
                          weekday: 'long',
                          day: 'numeric',
                          month: 'long',
                        })}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm opacity-90">Chi phí dự kiến</p>
                      <p className="font-bold">{formatCurrency(day.totalDayCost || 0)}</p>
                    </div>
                  </div>
                </div>

                <CardContent className="p-6 space-y-6">
                  {/* Morning */}
                  {day.morning && day.morning.activities && day.morning.activities.length > 0 && (
                    <div>
                      <div className="flex items-center gap-2 mb-3">
                        <div className="bg-yellow-100 p-2 rounded-full">
                          <Clock className="w-4 h-4 text-yellow-600" />
                        </div>
                        <div>
                          <p className="font-semibold">Buổi sáng</p>
                          <p className="text-sm text-gray-600">
                            Chi phí: {formatCurrency(day.morning.estimatedCost || 0)}
                          </p>
                        </div>
                      </div>
                      <ul className="space-y-2 ml-12">
                        {day.morning.activities.map((activity, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="text-blue-600 mt-1">•</span>
                            <span>{activity}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Afternoon */}
                  {day.afternoon && day.afternoon.activities && day.afternoon.activities.length > 0 && (
                    <div>
                      <div className="flex items-center gap-2 mb-3">
                        <div className="bg-orange-100 p-2 rounded-full">
                          <Clock className="w-4 h-4 text-orange-600" />
                        </div>
                        <div>
                          <p className="font-semibold">Buổi chiều</p>
                          <p className="text-sm text-gray-600">
                            Chi phí: {formatCurrency(day.afternoon.estimatedCost || 0)}
                          </p>
                        </div>
                      </div>
                      <ul className="space-y-2 ml-12">
                        {day.afternoon.activities.map((activity, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="text-blue-600 mt-1">•</span>
                            <span>{activity}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Evening */}
                  {day.evening && day.evening.activities && day.evening.activities.length > 0 && (
                    <div>
                      <div className="flex items-center gap-2 mb-3">
                        <div className="bg-purple-100 p-2 rounded-full">
                          <Clock className="w-4 h-4 text-purple-600" />
                        </div>
                        <div>
                          <p className="font-semibold">Buổi tối</p>
                          <p className="text-sm text-gray-600">
                            Chi phí: {formatCurrency(day.evening.estimatedCost || 0)}
                          </p>
                        </div>
                      </div>
                      <ul className="space-y-2 ml-12">
                        {day.evening.activities.map((activity, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="text-blue-600 mt-1">•</span>
                            <span>{activity}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Accommodation */}
                  {day.accommodation && (
                    <div className="border-t pt-4 mt-4">
                      <div className="flex items-center gap-2 text-gray-700">
                        <Home className="w-4 h-4" />
                        <span className="font-medium">Chỗ ở:</span>
                        <span>{day.accommodation}</span>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Transportation & Budget */}
        <div className="grid md:grid-cols-2 gap-6 mb-8">
          {/* Transportation */}
          {plan.transportation && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Train className="w-5 h-5" />
                  Phương tiện di chuyển
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <div>
                    <span className="text-gray-600">Loại:</span>
                    <span className="ml-2 font-medium capitalize">{plan.transportation.type}</span>
                  </div>
                  <div>
                    <span className="text-gray-600">Chi tiết:</span>
                    <p className="mt-1">{plan.transportation.details}</p>
                  </div>
                  <div>
                    <span className="text-gray-600">Chi phí:</span>
                    <span className="ml-2 font-medium">{formatCurrency(plan.transportation.cost || 0)}</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Budget Breakdown */}
          {plan.budgetBreakdown && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <DollarSign className="w-5 h-5" />
                  Phân bổ ngân sách
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {Object.entries(plan.budgetBreakdown).map(([key, value]) => {
                    if (key === 'total') return null;
                    const labels: Record<string, string> = {
                      transportation: 'Di chuyển',
                      accommodation: 'Chỗ ở',
                      food: 'Ăn uống',
                      activities: 'Hoạt động',
                      other: 'Khác',
                    };
                    const percentage = ((value / plan.budgetBreakdown.total) * 100).toFixed(0);
                    
                    return (
                      <div key={key}>
                        <div className="flex justify-between mb-1">
                          <span className="text-sm">{labels[key]}</span>
                          <span className="text-sm font-medium">{percentage}%</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-blue-600 h-2 rounded-full"
                            style={{ width: `${percentage}%` }}
                          />
                        </div>
                      </div>
                    );
                  })}
                  <div className="border-t pt-3 mt-3">
                    <div className="flex justify-between font-bold">
                      <span>Tổng cộng</span>
                      <span>{formatCurrency(plan.budgetBreakdown.total)}</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </div>

        {/* Tips */}
        {plan.tips && plan.tips.length > 0 && (
          <Card className="mb-8">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Lightbulb className="w-5 h-5 text-yellow-500" />
                💡 Tips quan trọng
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {plan.tips.map((tip, idx) => (
                  <li key={idx} className="flex items-start gap-2">
                    <span className="text-blue-600 mt-1">✓</span>
                    <span>{tip}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        )}

        {/* Warnings */}
        {plan.warnings && plan.warnings.length > 0 && (
          <Card className="border-yellow-200 bg-yellow-50 mb-8">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-yellow-900">
                <AlertTriangle className="w-5 h-5 text-yellow-600" />
                ⚠️ Lưu ý quan trọng
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {plan.warnings.map((warning, idx) => (
                  <li key={idx} className="flex items-start gap-2 text-yellow-900">
                    <span className="text-yellow-600 mt-1">⚠</span>
                    <span>{warning}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}

